In [1]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.8.0


In [4]:
tf.constant((5),shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 5],
       [5, 5],
       [5, 5]], dtype=int32)>

In [12]:
tf.ones((2,3),dtype='int32')

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [13]:
x= tf.random.normal((3,3), mean=0,stddev=1)
print(x)

tf.Tensor(
[[ 1.1642742  -0.49064     0.42177975]
 [ 0.00231983  0.90834105  0.8303198 ]
 [ 1.1540455   0.2786029   0.783231  ]], shape=(3, 3), dtype=float32)


In [20]:
x = tf.constant([1,2,3])
y = tf.constant([2,4,3])
z= tf.divide(x,y)

In [21]:
z

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.5, 0.5, 1. ])>

In [22]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [25]:
x = tf.reshape(x ,(3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [26]:
tf.transpose(x)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>

In [27]:
tf.transpose(x,perm=(1,0))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>

In [29]:
from tensorflow.keras.datasets import mnist

In [36]:
(x_train,y_train) , (x_test,y_test) = mnist.load_data()

In [40]:
x_train.shape

(60000, 28, 28)

In [39]:
x_test.shape

(10000, 28, 28)

In [41]:
x_train = x_train.reshape(-1,28*28)/255
x_test = x_test.reshape(-1,28*28)/255

In [43]:
from tensorflow.keras import layers

In [44]:
model = tf.keras.Sequential(
    [
        layers.Dense(500,activation= 'relu'),
        layers.Dense(250, activation='relu'),
        layers.Dense(10),

    ]
)

In [48]:
model.compile(
    loss= tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer='adam',
    metrics="accuracy"
)

In [50]:
model.fit(x_train,y_train,batch_size=23,epochs=5)
model.evaluate(x_test,y_test,batch_size=32)

Epoch 1/5
2609/2609 [==============================] - 20s 7ms/step - loss: 0.1836 - accuracy: 0.9445
Epoch 2/5
2609/2609 [==============================] - 17s 7ms/step - loss: 0.0815 - accuracy: 0.9744
Epoch 3/5
2609/2609 [==============================] - 17s 6ms/step - loss: 0.0561 - accuracy: 0.9822
Epoch 4/5
2609/2609 [==============================] - 17s 6ms/step - loss: 0.0445 - accuracy: 0.9861
Epoch 5/5
313/313 [==============================] - 1s 4ms/step - loss: 0.0756 - accuracy: 0.9805


[0.07562728226184845, 0.9804999828338623]